/**
 * share.js — Utilities for sharing and exporting itineraries
 */

/**
 * Generate a shareable URL with the trip data encoded in the hash
 */
export function generateShareLink(trip) {
  try {
    const data = JSON.stringify({
      t: trip.tripTitle,
      d: trip.destination,
      dur: trip.duration,
      b: trip.totalBudget,
      p: trip.persona,
      days: trip.days?.map(d => ({
        day: d.day,
        theme: d.theme,
        acts: d.activities?.map(a => ({ n: a.name, t: a.time, c: a.cost, desc: a.description }))
      }))
    });
    const encoded = btoa(unescape(encodeURIComponent(data)));
    return `${window.location.origin}/plan?shared=${encoded}`;
  } catch {
    return null;
  }
}

/**
 * Decode a shared trip from URL parameter
 */
export function decodeShareLink(encoded) {
  try {
    const json = decodeURIComponent(escape(atob(encoded)));
    const data = JSON.parse(json);
    return {
      tripTitle: data.t,
      destination: data.d,
      duration: data.dur,
      totalBudget: data.b,
      persona: data.p,
      days: data.days?.map(d => ({
        day: d.day,
        theme: d.theme,
        activities: d.acts?.map(a => ({
          name: a.n, time: a.t, cost: a.c, description: a.desc,
          type: 'sightseeing', duration: '2 hours', tip: '', accessibility: ''
        })),
        mealSuggestions: {}, dailyBudget: ''
      })),
      highlights: [], packingTips: [], budgetBreakdown: {}, emergencyContacts: {}, bestTimeToVisit: ''
    };
  } catch {
    return null;
  }
}

/**
 * Export itinerary as printable PDF (uses window.print)
 */
export function exportAsPDF(trip) {
  const content = buildPrintableHTML(trip);
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(content);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 500);
}

function buildPrintableHTML(trip) {
  const daysHTML = (trip.days || []).map(d => `
    <div style="margin-bottom:20px;page-break-inside:avoid">
      <h3 style="color:#6366f1">Day ${d.day}: ${d.theme}</h3>
      <table style="width:100%;border-collapse:collapse;font-size:13px">
        <tr style="background:#f3f4f6"><th style="text-align:left;padding:6px">Time</th><th style="text-align:left;padding:6px">Activity</th><th style="text-align:left;padding:6px">Cost</th></tr>
        ${(d.activities || []).map(a => `<tr><td style="padding:6px;border-bottom:1px solid #e5e7eb">${a.time}</td><td style="padding:6px;border-bottom:1px solid #e5e7eb"><strong>${a.name}</strong><br><span style="color:#666">${a.description || ''}</span></td><td style="padding:6px;border-bottom:1px solid #e5e7eb">${a.cost}</td></tr>`).join('')}
      </table>
    </div>
  `).join('');

  return `<!DOCTYPE html><html><head><title>${trip.tripTitle} — Wanderly</title>
    <style>body{font-family:system-ui,-apple-system,sans-serif;max-width:800px;margin:0 auto;padding:40px;color:#1a1a1a}h1{color:#6366f1}h2{color:#333;border-bottom:2px solid #6366f1;padding-bottom:8px}.meta{display:flex;gap:20px;color:#666;margin:10px 0 30px}</style>
    </head><body>
    <h1>${trip.tripTitle}</h1>
    <div class="meta"><span>📍 ${trip.destination}</span><span>📅 ${trip.duration}</span><span>💰 ${trip.totalBudget}</span><span>🎭 ${trip.persona}</span></div>
    <h2>Itinerary</h2>
    ${daysHTML}
    <hr><p style="text-align:center;color:#999;font-size:12px">Generated by Wanderly — AI Travel Planner · Powered by Google Gemini</p>
    </body></html>`;
}

/**
 * Native share API (works on mobile)
 */
export async function nativeShare(trip) {
  const text = `Check out my ${trip.duration} trip to ${trip.destination}: ${trip.tripTitle}!\n\nPlanned with Wanderly AI.`;
  const url = generateShareLink(trip);
  if (navigator.share) {
    try {
      await navigator.share({ title: trip.tripTitle, text, url });
      return true;
    } catch {
      return false;
    }
  }
  // Fallback: copy to clipboard
  try {
    await navigator.clipboard.writeText(url || text);
    return true;
  } catch {
    return false;
  }
}
